# Generated by Django 3.2 on 2024-04-13 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='images',
            field=models.ManyToManyField(blank=True, null=True, related_name='clients', to='todo.Image'),
        ),
    ]
